### ISSUE TITLE
Proposal for help

### ISSUE THREAD

**Issue by shreyasbapat** [williamFalcon/pytorch-lightning#1]
Hi @williamFalcon  ! I saw your project and I am very pleased by the idea. I wish to help you writing production level code.  PLease let me know in what way can I help!

**Comment by williamFalcon** [comment]
Sounds great. can you send me a pm on twitter? we can coordinate through there _willfalcon

**Comment by shreyasbapat** [comment]
Seems like on twitter both the sides have to follow each other in order to share PMs. Any other platform?

**Comment by williamFalcon** [comment]
good point haha. didn't know that about twitter. I've added you anyhow, but let's just chat here.

First step to helping is for you to do the following things and document your experience such as what was hard, what was not intuitive, what documentation would be helpful, etc.

1. Build and run the demo.
2. Build a simple classifier on your own using this.

From there we can see where the gaps are in usability and documentation. Then we can make a dev plan to get those things fixed in the library.

How does that sound? What's a good ETA to get that done?

Thanks!

**Comment by shreyasbapat** [comment]
Yes. I will do these after this week only. (I am too busy this week)

Anyways, the things that majorly concern me is the organisation of the package. You can have a look at my other library (Not related to DL) [EinsteinPy](https://github.com/einsteinpy/einsteinpy), but you can have a look at how extensively its tested etc. 

> From there we can see where the gaps are in usability and documentation. Then we can make a dev plan to get those things fixed in the library.

For this plan, I will get back to you this Tuesday?

**Comment by williamFalcon** [comment]
Sounds great. Yeah, this is a research library, so I didn't write tests for it because I've been moving quickly through research for publication. Tests would be great! I have however tested it myself when using/coding it, just didn't write an explicit test out.

Writing code for research has a less rigorous approach than code for a production system haha.

**Comment by shreyasbapat** [comment]
>  I have however tested it myself when using/coding it, just didn't write an explicit test out.

No issues! I would love to help. I will make some organisational changes in a PR, for making docs and CI easy! Is that fine?

**Comment by williamFalcon** [comment]
perfect. Looking forward!

**Comment by shreyasbapat** [comment]
One question. Why is the package name `pytorch_lightning` somewhere and `pytorch-lightning` somewhere else?

**Comment by shreyasbapat** [comment]
Oh! I am sorry, the tuesday thing got slipped off my mind. Will do this shortly :)

**Comment by williamFalcon** [comment]
Hi! lighting has been updated to include: tensorboard visualization, multi-gpu training, multi-node training, thoroughly documented and updated clean syntax. 

Would be auper helpful if you tried version 0.21 and provided feedback!

Thanks!

**Comment by 0560405608** [comment]
****
