### ISSUE TITLE
max_batches None leading to a full validation loop when val_percent_check is set

### ISSUE THREAD

**Issue by koustuvsinha** [williamFalcon/pytorch-lightning#160]
When I set `val_percent_check`, the value `max_batches` is None. Thus, [at this line](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L432) the validation loop continues to run till the full validation batch is done. I don't know why it should happen, but I see there is a check for None, so consider adding this line before:

```
if not max_batches:
    max_batches = self.nb_val_batches
```

**Comment by williamFalcon** [comment]
When you set nb_val_batches, [this line calculates the nb_val_batches:](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L363)   
```python    
        self.nb_val_batches = int(self.nb_val_batches * self.val_percent_check)
```

[If fast_dev_run is turned on, nb_val_batches = 1.  Otherwise, it uses whatever it calculated](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L1110).     
```python   
            max_batches = self.nb_val_batches if not self.fast_dev_run else 1
            for ds_i, dataloader in enumerate(self.val_dataloader):
                val_out_metrics = self.validate(self.model, dataloader, max_batches, ds_i)
```     

So, max_batches is never none. 
([because it is set here](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/models/trainer.py#L359)).   

But I do think there were recent fixes made on master. Install the master version?  
also cleaned that  up a bit

**Comment by williamFalcon** [comment]
See #163

**Comment by williamFalcon** [comment]
@koustuvsinha merged into master. try again? if it's none it's for another reason now. we can reopen if it continues
