### ISSUE TITLE
No real time Experiment logging

### ISSUE THREAD

**Issue by alex-obi** [williamFalcon/pytorch-lightning#28]
Currently I'm using your library in a simple setup

```
exp = Experiment(save_dir=save_dir)
trainer = Trainer(max_nb_epochs=1, experiment=exp)
trainer.fit(my_model)
```

on Google Colab. The folder _default/version_0/tf/_ gets immediently created, but sadly the tf experiment logs are only saved, when the training finished or got aborted by me by KeyboardInterrupt. So I can't watch the training process in tensorboard. Do you have any suggestions what to change to recieve real time updates?

**Comment by williamFalcon** [comment]
it’s probably finishing too quickly for logs to show up. remove max_nb_epochs or set to 50.

**Comment by williamFalcon** [comment]
Happy to reopen this issue if this doesn’t fix it. Enjoy the lightning!

**Comment by alex-obi** [comment]
On my local machine the same code updates the tensorboard file as expected every 100 samples.

Is it possible that there are any handles on the file that are open during training, but closed after? I remember a similar problem, where Google Colab Notebooks updated files only if all handles were closed.

**Comment by williamFalcon** [comment]
yeah, i think PyTorch SummaryWriter keeps a file open for saving. 

But i suspect the issue is with how Colab handles open files. PTL doesn’t keep any files open, it defaults to whatever the SummaryWriter behavior is. 

Glad to hear it’s fine on your local though. 

If you find out what the issue is on colab, def follow up here to see if there’s anything we can do on our end

https://pytorch.org/docs/stable/tensorboard.html

**Comment by williamFalcon** [comment]
@alex-obi update to latest test-tube version and try again?

pt 1.2.0
test tube 0.6.9
lightning 0.4.3
